name: build

on:
  push:
    branches:
      - main

jobs:
  build_memcached:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: Build package - Kafka
      build-args: |
        KAFKA_VERSION=3.4.1 # renovate: datasource=github-tags depName=apache/kafka
        SCALA_VERSION=2.13
      version: 3.4.1 # renovate: datasource=github-tags depName=apache/kafka
      revision: '3'
    secrets: inherit
